# Generated by Django 4.2.3 on 2023-07-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('courriel', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operateur', models.CharField(default='OM', max_length=100)),
            ],
        ),
    ]
