# Generated by Django 4.2.3 on 2023-07-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_currency_transaction_typetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id_receiver_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_sender_wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
